### PR TITLE
Fix Eclipse Integration

### LINKED ISSUE #40: Build failure when applied after the 'eclipse' plugin
I've just noticed that mixingradle 0.7-SNAPSHOT causes a build failure if the '**eclipse**' plugin is applied **before** the '**org.spongeforge.mixin**' plugin (it works fine the other way around).

It would be nice to see this fixed, as finding the cause was really time consuming with such an obscure error message from gradle.

Error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':forge-1.19:eclipseFactoryPath' (type 'MixinEclipse.EclipseFactoryPath').
  - In plugin 'org.spongepowered.mixin' type 'org.spongepowered.asm.gradle.plugins.MixinEclipse.EclipseFactoryPath' property 'config' has @Input annotation used on property of type 'Configuration'.

    Reason: A property of type 'Configuration' annotated with @Input cannot determine how to interpret the file.

    Possible solutions:
      1. Annotate with @InputFile for regular files.
      2. Annotate with @InputDirectory for directories.
      3. If you want to track the path, return File.absolutePath as a String and keep @Input.

    Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#incorrect_use_of_input_annotation for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
```

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR Fixes #40 and is a rebased version of #34 based on a commit by @CreativeMD (which is then based on a version by @DarkShadow44) https://github.com/CreativeMD/MixinGradle/commit/49453a0ba10258390879795316b8d3fd2fe914a5

It is recommended that eclipse users also apply the diffplug plugin so that the annotation processor can work correctly:
`id 'com.diffplug.eclipse.apt' version '3.42.2'`

### CODE REVIEW

File: src/main/groovy/org/spongepowered/asm/gradle/plugins/MixinEclipse.groovy [hunk 1]
```diff
@@ -53,6 +53,22 @@ public class MixinEclipse {
...
+                mappingsIn = extension.mappings
+                dependsOn project.tasks.createSrgToMcp
+                dependsOn project.tasks.createMcpToSrg
+                dependsOn project.tasks.eclipseJdtApt
+                hasDiffplug = true
+            }
+            project.tasks.eclipse.dependsOn(settings)
+            return
+        }
+        project.logger.warn '[MixinGradle] Use \'com.diffplug.eclipse.apt\' gradle plugin for full annotation support within eclipse'
```
Comment (SizableShrimp) [inline src/main/groovy/org/spongepowered/asm/gradle/plugins/MixinEclipse.groovy:70]: This should probably be in an else block so that it only logs if the apt plugin is not applied.

Additionally, does this mean users must apply 2 eclipse-related plugins?

Comment (Shadows-of-Fire) [reply src/main/groovy/org/spongepowered/asm/gradle/plugins/MixinEclipse.groovy:70]: 1) Probably, yeah

2) No, because it isn't strictly required - only if you need the AP support within eclipse - if there is a way we could make this plugin dep on diffplug and automatically pull it, that would be the best solution imo
